
version: '3.1'

services:
  adminmongo:
    image: mrautin/adminmongo
    ports:
      - 8001:1234
    environment:
      - HOST = 0.0.0.0
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ixT5Je7rUEqTdsPc


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ixT5Je7rUEqTdsPc
      ME_CONFIG_MONGODB_URL: mongodb+srv://root:ixT5Je7rUEqTdsPc@cluster0.jn9mf.mongodb.net/test?authSource=admin&replicaSet=atlas-11i8km-shard-0&readPreference=primary&ssl=true